// SPDX-License-Identifier: GPL-3.0-or-later
//! Does pm3-rs reproduce MOPAC's PM3? This is the file that answers it.
//!
//! `tests/data/mopac_oracle.tsv` holds MOPAC v23.2.5's own answers for 189 molecules
//! spanning **every element PM3 is parameterized for**, generated by
//! `tools/oracle/build_oracle_set.py`. Nothing in that file was computed here: each
//! geometry was optimized by MOPAC (or, for species with nothing to optimize, fixed), and
//! every number on the row comes from a MOPAC 1SCF at those coordinates. This file runs
//! pm3-rs on the same geometries and compares four independent things — the heat of
//! formation, the dipole, the net atomic charges and the Koopmans ionization potential.
//!
//! The charges and the dipole are not decoration. A misplaced one-center term can cancel in
//! the energy expression and survive in the density, so an energy-only comparison can agree
//! to six figures over a wrong wavefunction; comparing what MOPAC reports per atom closes
//! that, and the ionization potential closes the frontier of the spectrum.
//!
//! `tests/molecules.rs` is the older, hand-picked set — a dozen molecules chosen to
//! exercise one feature each, with the reference written into the source beside the
//! assertion. It stays as it is. This file exists because a dozen molecules cannot answer
//! "does the whole element set still reproduce MOPAC", and a set this wide found things a
//! dozen did not: seven molecules where the SCF had been converging to an excited solution,
//! and one where MOPAC's *default* was not PM3 at all (see
//! [`the_oracle_is_plain_pm3_not_mopacs_default`]).

use pm3_rs::corrections::mmok::AMIDE_K_KCAL;
use pm3_rs::params::Pm3Parameters;
use pm3_rs::scf::{run_pm3, Pm3Options, Pm3Result, ScfStability};
use pm3_rs::system::Molecule;
use std::collections::BTreeSet;

const TSV: &str = include_str!("data/mopac_oracle.tsv");

/// Agreement expected of every molecule. The measured worst case is `7.2e-4 kcal/mol`
/// (germane, where the heavy-element diatomic overlap is evaluated by quadrature here and
/// by a series expansion in MOPAC — the deviation characterised in
/// `tools/oracle/PM3_AUDIT.md`), so this is that bound with a little headroom. Tightening
/// it is a real improvement; loosening it means something changed.
const HOF_TOL_KCAL: f64 = 2.0e-3;
/// Measured worst case `1.1e-3` (the cyano radical).
const DIPOLE_TOL_DEBYE: f64 = 5.0e-3;
/// Measured worst case `1.6e-4` (gallium trichloride).
const CHARGE_TOL_E: f64 = 1.0e-3;
/// Relative bound, so that the capped-bond fixture is held to the same standard as the
/// rest. Its heat of formation is `-1.17e8 kcal/mol` — a MOPAC bookkeeping convention
/// rather than chemistry — and an absolute tolerance there would be either meaningless or
/// unmeetable.
const HOF_REL_TOL: f64 = 2.0e-9;

/// A few of these need more than the 200-iteration default; the methoxy radical is the
/// extreme. Raised rather than the molecules excused.
const MAX_SCF: usize = 2000;

struct Case {
    name: String,
    formula: String,
    charge: f64,
    multiplicity: usize,
    heat_of_formation_kcal: f64,
    dipole_debye: Option<f64>,
    ionization_potential_ev: Option<f64>,
    charges_e: Vec<f64>,
    relaxed: bool,
    symbols: Vec<String>,
    xyz: String,
}

fn cases() -> Vec<Case> {
    let mut out = Vec::new();
    for row in TSV.lines() {
        if row.starts_with('#') || row.starts_with("name\t") || row.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = row.split('\t').collect();
        assert_eq!(f.len(), 10, "row {:?} does not have ten columns", f.first());
        let atoms: Vec<&str> = f[9].split(';').collect();
        let name = f[0].to_string();
        let mut xyz = format!("{}\n{name}\n", atoms.len());
        let mut symbols = Vec::new();
        for atom in &atoms {
            xyz.push_str(atom);
            xyz.push('\n');
            symbols.push(atom.split_whitespace().next().unwrap().to_string());
        }
        let opt = |s: &str| (!s.is_empty()).then(|| s.parse::<f64>().unwrap());
        out.push(Case {
            name,
            formula: f[1].to_string(),
            charge: f[2].parse().unwrap(),
            multiplicity: f[3].parse().unwrap(),
            heat_of_formation_kcal: f[4].parse().unwrap(),
            dipole_debye: opt(f[5]),
            ionization_potential_ev: opt(f[6]),
            charges_e: if f[7].is_empty() {
                Vec::new()
            } else {
                f[7].split(';').map(|q| q.parse().unwrap()).collect()
            },
            relaxed: f[8] == "yes",
            symbols,
            xyz,
        });
    }
    out
}

fn run(case: &Case, options: Pm3Options) -> pm3_rs::Result<Pm3Result> {
    let mol = Molecule::from_xyz_str(&case.xyz, case.charge)
        .unwrap()
        .with_multiplicity(case.multiplicity);
    let params = Pm3Parameters::standard().unwrap();
    run_pm3(&mol, &params, &options)
}

fn defaults(case: &Case) -> Pm3Options {
    Pm3Options {
        charge: case.charge,
        multiplicity: case.multiplicity,
        max_scf: MAX_SCF,
        ..Pm3Options::default()
    }
}

/// Agreement to `HOF_TOL_KCAL` absolute, or `HOF_REL_TOL` relative for the huge ones.
fn agrees(ours: f64, mopac: f64) -> bool {
    let delta = (ours - mopac).abs();
    delta < HOF_TOL_KCAL || delta < HOF_REL_TOL * mopac.abs()
}

#[test]
fn the_oracle_carries_at_least_a_hundred_molecules() {
    let cases = cases();
    assert!(
        cases.len() >= 100,
        "the oracle set has shrunk to {} molecules",
        cases.len()
    );
    let names: BTreeSet<&str> = cases.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(names.len(), cases.len(), "duplicate names in the oracle");
}

/// **The headline test.** Heat of formation, dipole and net atomic charges for every
/// molecule, one SCF each.
#[test]
fn every_molecule_reproduces_mopac() {
    let mut checked = 0usize;
    let mut worst: (f64, String) = (0.0, String::new());
    for case in cases() {
        let result = run(&case, defaults(&case))
            .unwrap_or_else(|e| panic!("{} ({}) failed: {e}", case.name, case.formula));
        assert!(result.converged, "{} reported not converged", case.name);

        assert!(
            agrees(result.heat_of_formation_kcal, case.heat_of_formation_kcal),
            "{} ({}): pm3-rs {} vs MOPAC {} ({:.3e} kcal/mol)",
            case.name,
            case.formula,
            result.heat_of_formation_kcal,
            case.heat_of_formation_kcal,
            (result.heat_of_formation_kcal - case.heat_of_formation_kcal).abs()
        );
        let delta = (result.heat_of_formation_kcal - case.heat_of_formation_kcal).abs();
        if delta > worst.0 && delta < 1.0 {
            worst = (delta, case.name.clone());
        }

        if let Some(mopac) = case.dipole_debye {
            let d = result.dipole_debye;
            let ours = (d.x * d.x + d.y * d.y + d.z * d.z).sqrt();
            assert!(
                (ours - mopac).abs() < DIPOLE_TOL_DEBYE,
                "{}: dipole {ours} vs MOPAC {mopac} debye",
                case.name
            );
        }

        assert_eq!(
            result.charges.len(),
            case.charges_e.len(),
            "{}: charge count",
            case.name
        );
        for (i, (ours, mopac)) in result.charges.iter().zip(&case.charges_e).enumerate() {
            assert!(
                (ours - mopac).abs() < CHARGE_TOL_E,
                "{}: atom {} charge {ours} vs MOPAC {mopac}",
                case.name,
                i + 1
            );
        }
        checked += 1;
    }
    assert!(checked >= 100, "only {checked} molecules were compared");
    eprintln!(
        "{checked} molecules reproduce MOPAC; worst heat of formation {:.3e} kcal/mol ({})",
        worst.0, worst.1
    );
}

/// MOPAC's ionization potential is Koopmans' theorem on its own converged orbitals, so it
/// is minus the highest occupied orbital energy — comparing it checks the frontier of the
/// spectrum rather than only its sum. For an open shell the frontier is whichever of the
/// two spin HOMOs is higher, which is what `Pm3Result::homo_ev` reports and a naive
/// alpha-only reading would get wrong.
#[test]
fn the_frontier_orbital_matches_mopacs_koopmans_potential() {
    let mut checked = 0usize;
    for case in cases() {
        let Some(mopac_ip) = case.ionization_potential_ev else {
            continue;
        };
        let result = run(&case, defaults(&case)).unwrap();
        let Some(homo) = result.homo_ev else { continue };
        assert!(
            (-homo - mopac_ip).abs() < 1.0e-3,
            "{} ({}): -HOMO {} vs MOPAC IP {mopac_ip} eV",
            case.name,
            case.formula,
            -homo
        );
        checked += 1;
    }
    assert!(checked >= 100, "only {checked} frontier orbitals compared");
}

/// **Every element PM3 is parameterized for appears somewhere in the set.**
///
/// The one absentee is francium. Its row in `src/data/pm3_parameters.csv` is all zeros and
/// MOPAC answers `DATA ARE NOT AVAILABLE FOR ELEMENT NO. 87 ... CALCULATION STOPPED`, so
/// there is no PM3 to compare against; pm3-rs refuses it too, which is asserted below
/// rather than left implicit.
#[test]
fn the_oracle_covers_every_parameterized_element() {
    let mut seen = BTreeSet::new();
    for case in cases() {
        seen.extend(case.symbols);
    }
    let expected = [
        // Main group, the chemistry PM3 was fitted to.
        "Al", "As", "B", "Ba", "Be", "Bi", "Br", "C", "Ca", "Cd", "Cl", "Cs", "F", "Ga", "Ge", "H",
        "Hg", "I", "In", "K", "Li", "Mg", "N", "Na", "O", "P", "Pb", "Rb", "S", "Sb", "Se", "Si",
        "Sn", "Sr", "Te", "Tl", "Zn", // Noble gases, as fixed-separation dimers.
        "Ar", "He", "Kr", "Ne", "Xe", // MOPAC's three special atoms.
        "+", "-", "Cb", // The fifteen La-Lu Sparkles, as LnF3.
        "Ce", "Dy", "Er", "Eu", "Gd", "Ho", "La", "Lu", "Nd", "Pm", "Pr", "Sm", "Tb", "Tm", "Yb",
    ];
    for element in expected {
        assert!(
            seen.contains(element),
            "{element} is no longer in the oracle"
        );
    }
    assert_eq!(
        seen.len(),
        expected.len(),
        "the oracle gained or lost an element: {seen:?}"
    );
}

/// Francium: unsupported by both codes, and refused rather than silently answered.
#[test]
fn francium_is_refused_the_way_mopac_refuses_it() {
    let params = Pm3Parameters::standard().unwrap();
    let mol = Molecule::from_xyz_str("2\nFrCl\nFr 0 0 0\nCl 0 0 2.95\n", 0.0).unwrap();
    let error = run_pm3(&mol, &params, &Pm3Options::default())
        .expect_err("francium has no PM3 parameterization and must not return a number");
    let text = error.to_string();
    assert!(
        text.contains("87"),
        "the refusal should name the element: {text}"
    );
}

/// The stability search is load-bearing, not decoration.
///
/// Seven molecules in this set converge to an *excited* SCF solution from the default
/// starting point — self-consistent, obeying the aufbau principle among their own
/// eigenvalues, and wrong by up to 279 kcal/mol. `ScfStability::Auto` finds the lower
/// solution. This test turns the search off and checks that it still matters: if these
/// ever agree with the search disabled, the underlying convergence problem was fixed and
/// this test should record that instead.
#[test]
fn the_stability_search_is_what_makes_the_hard_cases_agree() {
    let hard = [
        "butyne",
        "ketene",
        "tetrafluoroethene",
        "tetrachloroethene",
        "methyl_radical",
    ];
    for name in hard {
        let case = cases().into_iter().find(|c| c.name == name).unwrap();
        let searched = run(&case, defaults(&case)).unwrap();
        assert!(
            agrees(searched.heat_of_formation_kcal, case.heat_of_formation_kcal),
            "{name} should agree with the search on"
        );
        assert!(
            searched.scf_paths_tried > 1,
            "{name} should have triggered the search"
        );
        assert!(
            searched.scf_improvement_ev > 1.0e-3,
            "{name} should have been rescued by the search, gained {} eV",
            searched.scf_improvement_ev
        );

        let unsearched = Pm3Options {
            stability: ScfStability::Off,
            ..defaults(&case)
        };
        let plain = run(&case, unsearched).unwrap();
        assert!(
            !agrees(plain.heat_of_formation_kcal, case.heat_of_formation_kcal),
            "{name} now agrees without the search — the SCF got better and this test is stale"
        );
        assert_eq!(plain.scf_paths_tried, 1);
    }
}

/// The search must not disturb the molecules that were already right.
#[test]
fn the_stability_search_changes_nothing_it_should_not() {
    let mut searched = 0usize;
    for case in cases() {
        let with = run(&case, defaults(&case)).unwrap();
        if with.scf_paths_tried > 1 {
            searched += 1;
            continue;
        }
        let without = run(
            &case,
            Pm3Options {
                stability: ScfStability::Off,
                ..defaults(&case)
            },
        )
        .unwrap();
        assert!(
            (with.heat_of_formation_kcal - without.heat_of_formation_kcal).abs() < 1e-12,
            "{}: the search altered a molecule it did not even search",
            case.name
        );
    }
    // It fires rarely, which is what keeps it affordable: the whole set solves in under a
    // second. A large jump here means the trigger has drifted and every caller pays for it.
    assert!(
        searched <= 20,
        "the stability search now fires on {searched} molecules; it used to be a handful"
    );
}

/// **MOPAC's default is not PM3.**
///
/// MOPAC applies `MMOK` unless told otherwise: a classical `K·sin²(O=C–N–H)` term added to
/// the heat of formation of any amide after the SCF. It changes no orbital and no total
/// energy, which is exactly why it is easy to mistake for a discrepancy — acetamide's
/// density, dipole and every eigenvalue agree with ours to six figures while its heat of
/// formation is 2.3 kcal/mol away.
///
/// The oracle is generated with `NOMM` for that reason, and pm3-rs defaults `mmok` to off.
/// This test pins both halves: our default reproduces MOPAC's `NOMM`, and our `mmok`
/// reproduces MOPAC's default.
#[test]
fn the_oracle_is_plain_pm3_not_mopacs_default() {
    let case = cases().into_iter().find(|c| c.name == "acetamide").unwrap();

    let plain = run(&case, defaults(&case)).unwrap();
    assert!(
        agrees(plain.heat_of_formation_kcal, case.heat_of_formation_kcal),
        "the default must reproduce MOPAC's NOMM: {} vs {}",
        plain.heat_of_formation_kcal,
        case.heat_of_formation_kcal
    );

    let corrected = run(
        &case,
        Pm3Options {
            mmok: true,
            ..defaults(&case)
        },
    )
    .unwrap();
    // MOPAC v23.2.5 at this geometry, default keywords (so, with MMOK): -48.7056462198816.
    const MOPAC_DEFAULT: f64 = -48.705_646_219_881_6;
    assert!(
        (corrected.heat_of_formation_kcal - MOPAC_DEFAULT).abs() < HOF_TOL_KCAL,
        "with mmok on we should reproduce MOPAC's default: {} vs {MOPAC_DEFAULT}",
        corrected.heat_of_formation_kcal
    );

    // The correction is post-SCF: it moves the heat of formation and nothing else.
    assert_eq!(plain.electronic_ev, corrected.electronic_ev);
    assert_eq!(plain.core_ev, corrected.core_ev);
    assert_eq!(plain.charges, corrected.charges);
    assert_eq!(plain.homo_ev, corrected.homo_ev);

    // And it is exactly `K · Σ sin²φ` over the two amide hydrogens, whose torsions at this
    // geometry are 27.730° and 160.879°. Computing the expected size from the published
    // constant rather than from a stored difference is what ties the constant to the
    // measurement instead of to itself.
    let applied = corrected.heat_of_formation_kcal - plain.heat_of_formation_kcal;
    let expected: f64 = AMIDE_K_KCAL
        * [27.730_f64, 160.879_f64]
            .iter()
            .map(|d| d.to_radians().sin().powi(2))
            .sum::<f64>();
    assert!(
        (applied - expected).abs() < 1.0e-3,
        "the amide term applied {applied} kcal/mol, K·Σsin²φ predicts {expected}"
    );
}

/// Species with nothing to relax are labelled as such, and are still real comparisons.
///
/// A noble-gas pair has no bound PM3 minimum and would fly apart; a Sparkle or a bare point
/// charge has no valence orbitals and so no chemistry to minimize. Their rows are single
/// points at a stated geometry, which is exactly what pm3-rs is asked to reproduce — so the
/// distinction is recorded in the file rather than left to be inferred.
#[test]
fn the_unrelaxed_fixtures_are_the_ones_with_nothing_to_relax() {
    let fixed: Vec<String> = cases()
        .into_iter()
        .filter(|c| !c.relaxed)
        .map(|c| c.name)
        .collect();
    assert!(
        !fixed.is_empty(),
        "the relaxed column has stopped being set"
    );
    for name in &fixed {
        let is_noble = name.ends_with("_dimer") || name == "helium_hydride_cation";
        let is_special = name.contains("sparkle") || name == "capped_methyl";
        let is_lanthanide = name.ends_with("_trifluoride");
        assert!(
            is_noble || is_special || is_lanthanide,
            "{name} is unrelaxed but is not one of the species that cannot be relaxed"
        );
    }
    // Everything else is a PM3 stationary point, which is what makes the frequencies and
    // gradients layered on these geometries elsewhere meaningful.
    let relaxed = cases().into_iter().filter(|c| c.relaxed).count();
    assert!(relaxed >= 100, "only {relaxed} relaxed fixtures");
}
